### ISSUE TITLE
Add CI to enforce some coding conventions and sanity checks

### ISSUE THREAD

**Issue by roata** [roata/roataway-telegram-bot#2]
Most likely it could be a mixture of `pylint` and `black`, to ensure that whoever sends pull requests will pass the minimum sanity checks, before an actual human has to look their code.

This will also help contributors help themselves

**Comment by roata** [comment]
The merge request that adds checks to the code was approved. The next step is to use a CI mechanism to automatically reject requests that don't meet the criteria, so contributors can get quick feedback and improve their work.

**Comment by PlugaruT** [comment]
I think we already have that :heavy_check_mark:

**Comment by roata** [comment]
Indeed.
